/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    float _field1;
    float _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    float _field1;
    float _field2;
};

struct GLKBigInt_s {
    unsigned long long n0;
    unsigned long long n1;
};

struct GLKEffectPropertyPrv {
    struct GLKBigInt_s *_field1;
    struct GLKBigInt_s *_field2;
    struct GLKBigInt_s *_field3;
    struct GLKBigInt_s *_field4;
};

#pragma mark Named Unions

union _GLKMatrix3 {
    struct {
        float m00;
        float m01;
        float m02;
        float m10;
        float m11;
        float m12;
        float m20;
        float m21;
        float m22;
    } ;
    float m[9];
};

union _GLKMatrix4 {
    struct {
        float m00;
        float m01;
        float m02;
        float m03;
        float m10;
        float m11;
        float m12;
        float m13;
        float m20;
        float m21;
        float m22;
        float m23;
        float m30;
        float m31;
        float m32;
        float m33;
    } ;
    float m[16];
};

union _GLKVector3 {
    struct {
        float x;
        float y;
        float z;
    } ;
    struct {
        float r;
        float g;
        float b;
    } ;
    struct {
        float s;
        float t;
        float p;
    } ;
    float v[3];
};

union _GLKVector4 {
    struct {
        float x;
        float y;
        float z;
        float w;
    } ;
    struct {
        float r;
        float g;
        float b;
        float a;
    } ;
    struct {
        float s;
        float t;
        float p;
        float q;
    } ;
    float v[4];
};

#pragma mark -

/*
 * File: /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk/System/Library/Frameworks/GLKit.framework/GLKit
 * UUID: 287DEFE3-060E-3EBD-B096-D85D39A569D3
 * Arch: arm v7 (armv7)
 *       Current version: 14.6.0, Compatibility version: 1.0.0
 *       Minimum iOS version: 5.0.0
 *
 *       Objective-C Garbage Collection: Unsupported
 */

@protocol GLKNamedEffect
- (void)prepareToDraw;
@end

@protocol GLKViewDelegate <NSObject>
- (void)glkView:(id)arg1 drawInRect:(struct CGRect)arg2;
@end

@protocol NSCoding
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@end

@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSObject
- (id)debugDescription;
- (id)description;
- (unsigned int)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
@end

@protocol NSXMLParserDelegate <NSObject>

@optional
- (void)parser:(id)arg1 validationErrorOccurred:(id)arg2;
- (void)parser:(id)arg1 parseErrorOccurred:(id)arg2;
- (id)parser:(id)arg1 resolveExternalEntityName:(id)arg2 systemID:(id)arg3;
- (void)parser:(id)arg1 foundCDATA:(id)arg2;
- (void)parser:(id)arg1 foundComment:(id)arg2;
- (void)parser:(id)arg1 foundProcessingInstructionWithTarget:(id)arg2 data:(id)arg3;
- (void)parser:(id)arg1 foundIgnorableWhitespace:(id)arg2;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 didEndMappingPrefix:(id)arg2;
- (void)parser:(id)arg1 didStartMappingPrefix:(id)arg2 toURI:(id)arg3;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parser:(id)arg1 foundExternalEntityDeclarationWithName:(id)arg2 publicID:(id)arg3 systemID:(id)arg4;
- (void)parser:(id)arg1 foundInternalEntityDeclarationWithName:(id)arg2 value:(id)arg3;
- (void)parser:(id)arg1 foundElementDeclarationWithName:(id)arg2 model:(id)arg3;
- (void)parser:(id)arg1 foundAttributeDeclarationWithName:(id)arg2 forElement:(id)arg3 type:(id)arg4 defaultValue:(id)arg5;
- (void)parser:(id)arg1 foundUnparsedEntityDeclarationWithName:(id)arg2 publicID:(id)arg3 systemID:(id)arg4 notationName:(id)arg5;
- (void)parser:(id)arg1 foundNotationDeclarationWithName:(id)arg2 publicID:(id)arg3 systemID:(id)arg4;
- (void)parserDidEndDocument:(id)arg1;
- (void)parserDidStartDocument:(id)arg1;
@end

@interface GLKBaseEffect : NSObject <GLKNamedEffect>
{
    unsigned char _colorMaterialEnabled;
    unsigned char _fogEnabled;
    GLKEffectPropertyTransform *_transform;
    int _lightingType;
    GLKEffectPropertyLight *_light0;
    GLKEffectPropertyLight *_light1;
    GLKEffectPropertyLight *_light2;
    GLKEffectPropertyMaterial *_material;
    GLKEffectPropertyTexture *_texture2d0;
    GLKEffectPropertyTexture *_texture2d1;
    NSArray *_textureOrder;
    union _GLKVector4 _constantColor;
    GLKEffectPropertyFog *_fog;
    NSString *_label;
    unsigned char _lightModelTwoSided;
    union _GLKVector4 _lightModelAmbientColor;
    GLKEffectPropertyConstantColor *_constantColorProp;
    unsigned char _useConstantColor;
    unsigned char _propertyArrayStale;
    NSMutableArray *_propertyArray;
    unsigned char _effectStale;
    GLKEffect *_effect;
    unsigned int _programName;
}

@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
@property(nonatomic) unsigned int programName; // @synthesize programName=_programName;
@property(nonatomic) GLKEffect *effect; // @synthesize effect=_effect;
@property(nonatomic) unsigned char effectStale; // @synthesize effectStale=_effectStale;
@property(readonly, nonatomic) NSMutableArray *propertyArray; // @synthesize propertyArray=_propertyArray;
@property(nonatomic) unsigned char propertyArrayStale; // @synthesize propertyArrayStale=_propertyArrayStale;
@property(nonatomic) unsigned char useConstantColor; // @synthesize useConstantColor=_useConstantColor;
@property(readonly, nonatomic) GLKEffectPropertyConstantColor *constantColorProp; // @synthesize constantColorProp=_constantColorProp;
@property(retain, nonatomic) NSArray *textureOrder; // @synthesize textureOrder=_textureOrder;
@property(nonatomic) union _GLKVector4 lightModelAmbientColor; // @synthesize lightModelAmbientColor=_lightModelAmbientColor;
@property(nonatomic) int lightingType; // @synthesize lightingType=_lightingType;
@property(readonly, nonatomic) GLKEffectPropertyTransform *transform; // @synthesize transform=_transform;
@property(nonatomic) unsigned char lightModelTwoSided; // @synthesize lightModelTwoSided=_lightModelTwoSided;
@property(nonatomic) unsigned char colorMaterialEnabled; // @synthesize colorMaterialEnabled=_colorMaterialEnabled;
- (void)dealloc;
- (id)description;
- (void)prepareToDraw;
- (void)updateBaseEffect;
- (BOOL)perPixelLightingEnabled;
- (BOOL)perVertexLightingEnabled;
@property(nonatomic) union _GLKVector4 constantColor; // @synthesize constantColor=_constantColor;
@property(readonly, nonatomic) GLKEffectPropertyFog *fog; // @synthesize fog=_fog;
@property(readonly, nonatomic) GLKEffectPropertyTexture *texture2d1; // @synthesize texture2d1=_texture2d1;
@property(readonly, nonatomic) GLKEffectPropertyTexture *texture2d0; // @synthesize texture2d0=_texture2d0;
@property(readonly, nonatomic) GLKEffectPropertyMaterial *material; // @synthesize material=_material;
@property(readonly, nonatomic) GLKEffectPropertyLight *light2; // @synthesize light2=_light2;
@property(readonly, nonatomic) GLKEffectPropertyLight *light1; // @synthesize light1=_light1;
@property(readonly, nonatomic) GLKEffectPropertyLight *light0; // @synthesize light0=_light0;
- (id)init;

@end

@interface GLKEffect : NSObject
{
    NSMutableArray *_properties;
    unsigned char _colorMaterialEnabled;
    unsigned char _lightModelTwoSided;
    union _GLKVector4 _lightModelAmbientColor;
    unsigned char _texturingEnabled;
    NSArray *_textureOrder;
    NSString *_label;
    NSMutableDictionary *_programHash;
    unsigned char _perVertexLightingEnabled;
    unsigned char _perPixelLightingEnabled;
    unsigned int _numLights;
    unsigned int _numTextures;
    float *_materialAmbientColor;
    float *_materialDiffuseColor;
    union _GLKVector4 _baseLightingColor;
    union _GLKVector4 _white;
    unsigned char _masksInitialized;
    id *_effectShaderArray;
    NSMutableArray *_lightProperties;
    GLKShaderBlockNode *_vshRootNode;
    GLKShaderBlockNode *_fshRootNode;
    unsigned int _vshName;
    unsigned int _fshName;
    unsigned int _programName;
    char **_vshStrings;
    char **_fshStrings;
    unsigned int _numVshStrings;
    unsigned int _numFshStrings;
    unsigned long long _dirtyUniforms;
    _Bool _programStale;
    _Bool _textureOrderStale;
    int _lightModelAmbientColorLoc;
    int _baseLightingColorLoc;
    struct GLKBigInt_s *_fshMask;
    struct GLKBigInt_s *_vshMask;
    struct GLKBigInt_s _prevFshMask;
    struct GLKBigInt_s _prevVshMask;
}

+ (void)setStaticMasksWithVshRoot:(id)arg1 fshRoot:(id)arg2;
+ (id)shaderInfoLogForName:(unsigned int)arg1 effectLabel:(id)arg2 msg:(const char *)arg3;
+ (id)programInfoLogForName:(unsigned int)arg1 effectLabel:(id)arg2 msg:(const char *)arg3;
@property(nonatomic) struct GLKBigInt_s prevVshMask; // @synthesize prevVshMask=_prevVshMask;
@property(nonatomic) struct GLKBigInt_s prevFshMask; // @synthesize prevFshMask=_prevFshMask;
@property(nonatomic) struct GLKBigInt_s *vshMask; // @synthesize vshMask=_vshMask;
@property(nonatomic) struct GLKBigInt_s *fshMask; // @synthesize fshMask=_fshMask;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
@property(nonatomic) int baseLightingColorLoc; // @synthesize baseLightingColorLoc=_baseLightingColorLoc;
@property(nonatomic) int lightModelAmbientColorLoc; // @synthesize lightModelAmbientColorLoc=_lightModelAmbientColorLoc;
@property(nonatomic) _Bool textureOrderStale; // @synthesize textureOrderStale=_textureOrderStale;
@property(nonatomic) _Bool programStale; // @synthesize programStale=_programStale;
@property(nonatomic) unsigned long long dirtyUniforms; // @synthesize dirtyUniforms=_dirtyUniforms;
@property(nonatomic) unsigned int numFshStrings; // @synthesize numFshStrings=_numFshStrings;
@property(nonatomic) unsigned int numVshStrings; // @synthesize numVshStrings=_numVshStrings;
@property(nonatomic) char **fshStrings; // @synthesize fshStrings=_fshStrings;
@property(nonatomic) char **vshStrings; // @synthesize vshStrings=_vshStrings;
@property(nonatomic) unsigned int programName; // @synthesize programName=_programName;
@property(nonatomic) unsigned int fshName; // @synthesize fshName=_fshName;
@property(nonatomic) unsigned int vshName; // @synthesize vshName=_vshName;
@property(readonly, nonatomic) GLKShaderBlockNode *fshRootNode; // @synthesize fshRootNode=_fshRootNode;
@property(readonly, nonatomic) GLKShaderBlockNode *vshRootNode; // @synthesize vshRootNode=_vshRootNode;
@property(retain, nonatomic) NSArray *textureOrder; // @synthesize textureOrder=_textureOrder;
@property(retain, nonatomic) NSMutableArray *lightProperties; // @synthesize lightProperties=_lightProperties;
@property(nonatomic) id *effectShaderArray; // @synthesize effectShaderArray=_effectShaderArray;
@property(nonatomic) unsigned char masksInitialized; // @synthesize masksInitialized=_masksInitialized;
@property(nonatomic) union _GLKVector4 white; // @synthesize white=_white;
@property(nonatomic) union _GLKVector4 baseLightingColor; // @synthesize baseLightingColor=_baseLightingColor;
@property(readonly, nonatomic) float *materialDiffuseColor; // @synthesize materialDiffuseColor=_materialDiffuseColor;
@property(readonly, nonatomic) float *materialAmbientColor; // @synthesize materialAmbientColor=_materialAmbientColor;
@property(nonatomic) unsigned char texturingEnabled; // @synthesize texturingEnabled=_texturingEnabled;
@property(nonatomic) union _GLKVector4 lightModelAmbientColor; // @synthesize lightModelAmbientColor=_lightModelAmbientColor;
@property(nonatomic) unsigned char lightModelTwoSided; // @synthesize lightModelTwoSided=_lightModelTwoSided;
@property(nonatomic) unsigned char colorMaterialEnabled; // @synthesize colorMaterialEnabled=_colorMaterialEnabled;
@property(nonatomic) unsigned int numTextures; // @synthesize numTextures=_numTextures;
@property(nonatomic) unsigned int numLights; // @synthesize numLights=_numLights;
@property(nonatomic) unsigned char perPixelLightingEnabled; // @synthesize perPixelLightingEnabled=_perPixelLightingEnabled;
@property(nonatomic) unsigned char perVertexLightingEnabled; // @synthesize perVertexLightingEnabled=_perVertexLightingEnabled;
@property(readonly, nonatomic) NSMutableDictionary *programHash; // @synthesize programHash=_programHash;
@property(retain, nonatomic) NSMutableArray *properties; // @synthesize properties=_properties;
- (void)dealloc;
- (char **)fshMaskStr;
- (char **)vshMaskStr;
- (unsigned int)fshMaskCt;
- (unsigned int)vshMaskCt;
- (struct GLKBigInt_s *)fshMasks;
- (struct GLKBigInt_s *)vshMasks;
- (id)description;
- (_Bool)includeShaderTextForRootNode:(id)arg1;
- (void)initializeMasks;
- (void)bind;
- (void)createAndUseProgramWithShadingHash:(id)arg1;
- (void)logFshMasks;
- (void)logVshMasks;
- (void)updateFshStringsWithRoot:(id)arg1 enabled:(struct GLKBigInt_s)arg2;
- (void)updateVshStringsWithRoot:(id)arg1 enabled:(struct GLKBigInt_s)arg2;
- (void)setShaderBindings;
- (void)lightStateChanged;
- (void)lightModelTwoSidedMask;
- (BOOL)useColorAttrib;
- (BOOL)useTexCoordAttrib;
- (void)setTextureNameStrings;
- (void)addTransformProperty;
- (void)dirtyAllUniforms;
- (id)initWithPropertyArray:(id)arg1;
- (void)unrollLoopNodesForStaticTreeWithRoot:(id)arg1;
- (_Bool)parseXMLFile:(id)arg1 rootNode:(id)arg2;
- (void)vPositionEyeMask;
- (void)vNormalEyeMask;
- (void)normalizedNormalsMask;
- (void)texturingEnabledMask;
- (void)useTexCoordAttribMask;
- (void)initializeStaticMasks;
- (id)init;

@end

@interface GLKEffectProperty : NSObject
{
    int _location;
    char *_nameString;
    struct GLKEffectPropertyPrv *_prv;
    char *_vshSource;
    char *_fshSource;
    unsigned long long _dirtyUniforms;
    GLKEffect *_effect;
    unsigned char _masksInitialized;
}

+ (void)logSetMasksWithLabel:(id)arg1 obj:(id)arg2 typeStr:(id)arg3;
+ (void)setStaticMasksWithVshRoot:(id)arg1 fshRoot:(id)arg2;
@property(nonatomic) unsigned char masksInitialized; // @synthesize masksInitialized=_masksInitialized;
@property(nonatomic) GLKEffect *effect; // @synthesize effect=_effect;
@property(nonatomic) unsigned long long dirtyUniforms; // @synthesize dirtyUniforms=_dirtyUniforms;
@property(nonatomic) char *fshSource; // @synthesize fshSource=_fshSource;
@property(nonatomic) char *vshSource; // @synthesize vshSource=_vshSource;
@property(nonatomic) char *nameString; // @synthesize nameString=_nameString;
@property(nonatomic) int location; // @synthesize location=_location;
- (void)dealloc;
- (struct GLKBigInt_s *)fshMask;
- (struct GLKBigInt_s *)vshMask;
- (void)dirtyAllUniforms;
- (void)bind;
- (void)initializeMasks;
- (void)setMasks;
- (_Bool)includeShaderTextForRootNode:(id)arg1;
- (void)setShaderBindings;
- (void)setFSHSource:(char *)arg1;
- (void)setVSHSource:(char *)arg1;
- (id)init;

@end

@interface GLKEffectPropertyConstantColor : GLKEffectProperty
{
    union _GLKVector4 _color;
    unsigned char _enabled;
}

+ (void)setStaticMasksWithVshRoot:(id)arg1 fshRoot:(id)arg2;
@property(nonatomic) unsigned char enabled; // @synthesize enabled=_enabled;
@property(nonatomic) union _GLKVector4 color; // @synthesize color=_color;
- (void)dealloc;
- (char **)fshMaskStr;
- (char **)vshMaskStr;
- (unsigned int)fshMaskCt;
- (unsigned int)vshMaskCt;
- (struct GLKBigInt_s *)fshMasks;
- (struct GLKBigInt_s *)vshMasks;
- (id)description;
- (void)bind;
- (void)setShaderBindings;
- (void)dirtyAllUniforms;
- (id)init;

@end

@interface GLKEffectPropertyFog : GLKEffectProperty
{
    unsigned char _enabled;
    int _mode;
    union _GLKVector4 _color;
    float _density;
    float _start;
    float _end;
    int _modeLoc;
    int _colorLoc;
    int _densityLoc;
    int _startLoc;
    int _endLoc;
}

+ (void)setStaticMasksWithVshRoot:(id)arg1 fshRoot:(id)arg2;
@property(nonatomic) int endLoc; // @synthesize endLoc=_endLoc;
@property(nonatomic) int startLoc; // @synthesize startLoc=_startLoc;
@property(nonatomic) int densityLoc; // @synthesize densityLoc=_densityLoc;
@property(nonatomic) int colorLoc; // @synthesize colorLoc=_colorLoc;
@property(nonatomic) int modeLoc; // @synthesize modeLoc=_modeLoc;
@property(nonatomic) float end; // @synthesize end=_end;
@property(nonatomic) float start; // @synthesize start=_start;
@property(nonatomic) float density; // @synthesize density=_density;
@property(nonatomic) union _GLKVector4 color; // @synthesize color=_color;
@property(nonatomic) int mode; // @synthesize mode=_mode;
@property(nonatomic) unsigned char enabled; // @synthesize enabled=_enabled;
- (void)dealloc;
- (char **)fshMaskStr;
- (char **)vshMaskStr;
- (unsigned int)fshMaskCt;
- (unsigned int)vshMaskCt;
- (struct GLKBigInt_s *)fshMasks;
- (struct GLKBigInt_s *)vshMasks;
- (void)bind;
- (void)setShaderBindings;
- (_Bool)includeShaderTextForRootNode:(id)arg1;
- (void)initializeMasks;
- (void)dirtyAllUniforms;
- (id)init;

@end

@interface GLKEffectPropertyLight : GLKEffectProperty
{
    unsigned char _enabled;
    union _GLKVector4 _position;
    union _GLKVector4 _ambientColor;
    union _GLKVector4 _diffuseColor;
    union _GLKVector4 _specularColor;
    union _GLKVector3 _spotDirection;
    float _spotExponent;
    float _spotCutoff;
    float _constantAttenuation;
    float _linearAttenuation;
    float _quadraticAttenuation;
    GLKEffectPropertyTransform *_transform;
    union _GLKVector4 _positionEye;
    union _GLKVector4 _white;
    union _GLKVector3 _normalizedSpotDirectionEye;
    float _spotCutoffDegrees;
    unsigned long long *_effectDirtyUniforms;
    unsigned char _positionEyeStale;
    int _positionEyeLoc;
    int _ambientLoc;
    int _diffuseLoc;
    int _specularLoc;
    int _normalizedSpotDirectionEyeLoc;
    int _spotExponentLoc;
    int _spotCutoffLoc;
    int _constantAttenuationLoc;
    int _linearAttenuationLoc;
    int _quadraticAttenuationLoc;
    int _normalizeLoc;
    int _ambientTermLoc;
    int _lightIndex;
    int _lightingType;
    unsigned char _firstLight;
    unsigned char _useConstantColor;
}

+ (void)setStaticMasksWithVshRoot:(id)arg1 fshRoot:(id)arg2;
+ (id)effectPropertyWithAttrib:(int)arg1;
@property(nonatomic) unsigned char useConstantColor; // @synthesize useConstantColor=_useConstantColor;
@property(nonatomic) unsigned char firstLight; // @synthesize firstLight=_firstLight;
@property(nonatomic) int lightingType; // @synthesize lightingType=_lightingType;
@property(nonatomic) int lightIndex; // @synthesize lightIndex=_lightIndex;
@property(nonatomic) int ambientTermLoc; // @synthesize ambientTermLoc=_ambientTermLoc;
@property(nonatomic) int normalizeLoc; // @synthesize normalizeLoc=_normalizeLoc;
@property(nonatomic) int quadraticAttenuationLoc; // @synthesize quadraticAttenuationLoc=_quadraticAttenuationLoc;
@property(nonatomic) int linearAttenuationLoc; // @synthesize linearAttenuationLoc=_linearAttenuationLoc;
@property(nonatomic) int constantAttenuationLoc; // @synthesize constantAttenuationLoc=_constantAttenuationLoc;
@property(nonatomic) int spotCutoffLoc; // @synthesize spotCutoffLoc=_spotCutoffLoc;
@property(nonatomic) int spotExponentLoc; // @synthesize spotExponentLoc=_spotExponentLoc;
@property(nonatomic) int normalizedSpotDirectionEyeLoc; // @synthesize normalizedSpotDirectionEyeLoc=_normalizedSpotDirectionEyeLoc;
@property(nonatomic) int specularLoc; // @synthesize specularLoc=_specularLoc;
@property(nonatomic) int diffuseLoc; // @synthesize diffuseLoc=_diffuseLoc;
@property(nonatomic) int ambientLoc; // @synthesize ambientLoc=_ambientLoc;
@property(nonatomic) int positionEyeLoc; // @synthesize positionEyeLoc=_positionEyeLoc;
@property(nonatomic) unsigned char positionEyeStale; // @synthesize positionEyeStale=_positionEyeStale;
@property(retain, nonatomic) GLKEffectPropertyTransform *transform; // @synthesize transform=_transform;
@property(nonatomic) unsigned long long *effectDirtyUniforms; // @synthesize effectDirtyUniforms=_effectDirtyUniforms;
@property(nonatomic) float quadraticAttenuation; // @synthesize quadraticAttenuation=_quadraticAttenuation;
@property(nonatomic) float linearAttenuation; // @synthesize linearAttenuation=_linearAttenuation;
@property(nonatomic) float constantAttenuation; // @synthesize constantAttenuation=_constantAttenuation;
@property(nonatomic) float spotCutoffDegrees; // @synthesize spotCutoffDegrees=_spotCutoffDegrees;
@property(nonatomic) float spotExponent; // @synthesize spotExponent=_spotExponent;
@property(nonatomic) union _GLKVector3 normalizedSpotDirectionEye; // @synthesize normalizedSpotDirectionEye=_normalizedSpotDirectionEye;
@property(nonatomic) union _GLKVector4 white; // @synthesize white=_white;
@property(nonatomic) union _GLKVector3 spotDirection; // @synthesize spotDirection=_spotDirection;
@property(nonatomic) union _GLKVector4 specularColor; // @synthesize specularColor=_specularColor;
@property(nonatomic) union _GLKVector4 diffuseColor; // @synthesize diffuseColor=_diffuseColor;
@property(nonatomic) union _GLKVector4 ambientColor; // @synthesize ambientColor=_ambientColor;
@property(nonatomic) union _GLKVector4 positionEye; // @synthesize positionEye=_positionEye;
@property(nonatomic) union _GLKVector4 position; // @synthesize position=_position;
@property(nonatomic) unsigned char enabled; // @synthesize enabled=_enabled;
- (void)dealloc;
- (char **)fshMaskStr;
- (char **)vshMaskStr;
- (unsigned int)fshMaskCt;
- (unsigned int)vshMaskCt;
- (struct GLKBigInt_s *)fshMasks;
- (struct GLKBigInt_s *)vshMasks;
- (void)bind;
- (void)attenuateMask;
@property(readonly, nonatomic) unsigned char isAttenuated;
- (void)spotMask;
@property(readonly, nonatomic) unsigned char isSpot;
- (void)enabledMask;
- (void)directionalLightMask;
- (void)positionalLightMask;
- (_Bool)includeShaderTextForRootNode:(id)arg1;
- (void)setMasks;
@property(nonatomic) float spotCutoff; // @synthesize spotCutoff=_spotCutoff;
- (void)setNormalize:(unsigned char)arg1;
- (void)setShaderBindings;
- (void)initializeMasks;
- (void)setGLDefaults;
- (void)dirtyAllUniforms;
- (id)initWithTransform:(id)arg1 lightingType:(int)arg2 firstLight:(unsigned char)arg3 useConstantColor:(unsigned char)arg4;

@end

@interface GLKEffectPropertyMaterial : GLKEffectProperty
{
    union _GLKVector4 _ambientColor;
    union _GLKVector4 _diffuseColor;
    union _GLKVector4 _specularColor;
    union _GLKVector4 _emissiveColor;
    float _shininess;
    unsigned long long *_effectDirtyUniforms;
    int _ambientColorLoc;
    int _diffuseColorLoc;
    int _specularColorLoc;
    int _emissiveColorLoc;
    int _shininessLoc;
    struct GLKBigInt_s _colorMaterialEnabledMask;
}

+ (void)setStaticMasksWithVshRoot:(id)arg1 fshRoot:(id)arg2;
@property(nonatomic) struct GLKBigInt_s _colorMaterialEnabledMask; // @synthesize _colorMaterialEnabledMask;
@property(nonatomic) int _shininessLoc; // @synthesize _shininessLoc;
@property(nonatomic) int _emissiveColorLoc; // @synthesize _emissiveColorLoc;
@property(nonatomic) int _specularColorLoc; // @synthesize _specularColorLoc;
@property(nonatomic) int _diffuseColorLoc; // @synthesize _diffuseColorLoc;
@property(nonatomic) int _ambientColorLoc; // @synthesize _ambientColorLoc;
@property(nonatomic) unsigned long long *effectDirtyUniforms; // @synthesize effectDirtyUniforms=_effectDirtyUniforms;
@property(nonatomic) float shininess; // @synthesize shininess=_shininess;
@property(nonatomic) union _GLKVector4 emissiveColor; // @synthesize emissiveColor=_emissiveColor;
@property(nonatomic) union _GLKVector4 specularColor; // @synthesize specularColor=_specularColor;
@property(nonatomic) union _GLKVector4 diffuseColor; // @synthesize diffuseColor=_diffuseColor;
@property(nonatomic) union _GLKVector4 ambientColor; // @synthesize ambientColor=_ambientColor;
- (void)dealloc;
- (char **)fshMaskStr;
- (char **)vshMaskStr;
- (unsigned int)fshMaskCt;
- (unsigned int)vshMaskCt;
- (struct GLKBigInt_s *)fshMasks;
- (struct GLKBigInt_s *)vshMasks;
- (void)bind;
- (_Bool)includeShaderTextForRootNode:(id)arg1;
- (void)setShaderBindings;
- (void)specularColorMask;
- (void)initializeMasks;
- (void)dirtyAllUniforms;
- (id)init;

@end

@interface GLKEffectPropertyTexGen : GLKEffectProperty
{
    int _mode;
    float *_plane;
    int _coord;
    float *_eyePlaneByInvModelview;
    int _modeLoc;
    int _planeLoc;
    int _eyePlaneByInvModelviewLoc;
    char *_modeNameString;
    char *_planeNameString;
    unsigned int _textureIndex;
}

@property(nonatomic) unsigned int textureIndex; // @synthesize textureIndex=_textureIndex;
@property(nonatomic) char *planeNameString; // @synthesize planeNameString=_planeNameString;
@property(nonatomic) char *modeNameString; // @synthesize modeNameString=_modeNameString;
@property(nonatomic) int eyePlaneByInvModelviewLoc; // @synthesize eyePlaneByInvModelviewLoc=_eyePlaneByInvModelviewLoc;
@property(nonatomic) int planeLoc; // @synthesize planeLoc=_planeLoc;
@property(nonatomic) int modeLoc; // @synthesize modeLoc=_modeLoc;
@property(nonatomic) float *eyePlaneByInvModelview; // @synthesize eyePlaneByInvModelview=_eyePlaneByInvModelview;
@property(readonly, nonatomic) int coord; // @synthesize coord=_coord;
@property(nonatomic) float *plane; // @synthesize plane=_plane;
@property(nonatomic) int mode; // @synthesize mode=_mode;
- (void)dealloc;
- (char **)fshMaskStr;
- (char **)vshMaskStr;
- (unsigned int)fshMaskCt;
- (unsigned int)vshMaskCt;
- (struct GLKBigInt_s *)fshMasks;
- (struct GLKBigInt_s *)vshMasks;
- (void)bind;
- (void)initializeMasks;
- (void)setShaderBindings;
- (void)dirtyAllUniforms;
- (id)initWithMode:(int)arg1 coord:(int)arg2;
- (id)init;

@end

@interface GLKEffectPropertyTexture : GLKEffectProperty
{
    unsigned char _enabled;
    unsigned int _name;
    int _target;
    int _envMode;
    NSString *_filePath;
    int _textureIndex;
    unsigned char _matrixEnabled;
    char *_unit2dNameString;
    char *_unitCubeNameString;
    int _unit2dLoc;
    int _unitCubeLoc;
    NSMutableArray *_texGenArray;
    GLKEffectPropertyTexGen *_texGenS;
    GLKEffectPropertyTexGen *_texGenT;
    GLKEffectPropertyTexGen *_texGenR;
}

+ (void)setStaticMasksWithVshRoot:(id)arg1 fshRoot:(id)arg2;
@property(readonly, nonatomic) NSMutableArray *texGenArray; // @synthesize texGenArray=_texGenArray;
@property(nonatomic) int unitCubeLoc; // @synthesize unitCubeLoc=_unitCubeLoc;
@property(nonatomic) int unit2dLoc; // @synthesize unit2dLoc=_unit2dLoc;
@property(nonatomic) unsigned int name; // @synthesize name=_name;
@property(nonatomic) char *unitCubeNameString; // @synthesize unitCubeNameString=_unitCubeNameString;
@property(nonatomic) char *unit2dNameString; // @synthesize unit2dNameString=_unit2dNameString;
@property(nonatomic) int envMode; // @synthesize envMode=_envMode;
@property(nonatomic) unsigned char matrixEnabled; // @synthesize matrixEnabled=_matrixEnabled;
@property(nonatomic) int textureIndex; // @synthesize textureIndex=_textureIndex;
@property(readonly, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) unsigned char enabled; // @synthesize enabled=_enabled;
@property(nonatomic) int target; // @synthesize target=_target;
- (void)dealloc;
- (char **)fshMaskStr;
- (char **)vshMaskStr;
- (unsigned int)fshMaskCt;
- (unsigned int)vshMaskCt;
- (struct GLKBigInt_s *)fshMasks;
- (struct GLKBigInt_s *)vshMasks;
- (void)bind;
- (id)description;
@property(readonly, nonatomic) unsigned char useTexCoordAttribMask;
@property(readonly, nonatomic) unsigned char vNormalEyeMask;
@property(readonly, nonatomic) unsigned char vPositionEyeMask;
@property(readonly, nonatomic) unsigned char normalizedNormalsMask;
- (void)initializeMasks;
- (_Bool)includeShaderTextForRootNode:(id)arg1;
- (void)texGenMask;
- (void)reflectionMapMask;
- (void)setMasks;
- (void)setShaderBindings;
@property(readonly, nonatomic) GLKEffectPropertyTexGen *texGenR; // @synthesize texGenR=_texGenR;
@property(readonly, nonatomic) GLKEffectPropertyTexGen *texGenT; // @synthesize texGenT=_texGenT;
@property(readonly, nonatomic) GLKEffectPropertyTexGen *texGenS; // @synthesize texGenS=_texGenS;
- (void)dirtyAllUniforms;
- (id)init;

@end

@interface GLKEffectPropertyTransform : GLKEffectProperty
{
    union _GLKMatrix4 _modelviewMatrix;
    union _GLKMatrix4 _projectionMatrix;
    union _GLKMatrix3 _normalMatrix;
    union _GLKMatrix4 _invModelviewMatrix;
    union _GLKMatrix4 _mvpMatrix;
    int _mvpMatrixLoc;
    int _modelviewMatrixLoc;
    int _projectionMatrixLoc;
    int _normalMatrixLoc;
    int _invModelviewMatrixLoc;
}

+ (void)setStaticMasksWithVshRoot:(id)arg1 fshRoot:(id)arg2;
@property(nonatomic) int invModelviewMatrixLoc; // @synthesize invModelviewMatrixLoc=_invModelviewMatrixLoc;
@property(nonatomic) int normalMatrixLoc; // @synthesize normalMatrixLoc=_normalMatrixLoc;
@property(nonatomic) int projectionMatrixLoc; // @synthesize projectionMatrixLoc=_projectionMatrixLoc;
@property(nonatomic) int modelviewMatrixLoc; // @synthesize modelviewMatrixLoc=_modelviewMatrixLoc;
@property(nonatomic) int mvpMatrixLoc; // @synthesize mvpMatrixLoc=_mvpMatrixLoc;
@property(nonatomic) union _GLKMatrix4 mvpMatrix; // @synthesize mvpMatrix=_mvpMatrix;
@property(nonatomic) union _GLKMatrix4 invModelviewMatrix; // @synthesize invModelviewMatrix=_invModelviewMatrix;
@property(nonatomic) union _GLKMatrix4 projectionMatrix; // @synthesize projectionMatrix=_projectionMatrix;
@property(nonatomic) union _GLKMatrix4 modelviewMatrix; // @synthesize modelviewMatrix=_modelviewMatrix;
- (void)dealloc;
- (id)description;
- (void)bind;
@property(readonly, nonatomic) union _GLKMatrix3 normalMatrix; // @synthesize normalMatrix=_normalMatrix;
- (void)setShaderBindings;
- (void)loadMatrix:(int)arg1 matrix:(union _GLKMatrix4)arg2;
- (void)loadIdentity:(int)arg1;
- (void)dirtyAllUniforms;
- (id)init;

@end

@interface GLKEffectTexture : NSObject
{
    NSMutableArray *_imageData;
    unsigned int _name;
    unsigned int _width;
    unsigned int _height;
    unsigned int _internalFormat;
    BOOL _hasAlpha;
}

+ (id)textureWithContentsOfURL:(id)arg1;
+ (id)textureWithContentsOfFile:(id)arg1;
@property(readonly, nonatomic) BOOL hasAlpha; // @synthesize hasAlpha=_hasAlpha;
@property(readonly, nonatomic) unsigned int internalFormat; // @synthesize internalFormat=_internalFormat;
@property(readonly, nonatomic) unsigned int height; // @synthesize height=_height;
@property(readonly, nonatomic) unsigned int width; // @synthesize width=_width;
@property(readonly, nonatomic) unsigned int name; // @synthesize name=_name;
- (void)dealloc;
- (id)initWithContentsOfURL:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (BOOL)createGLTexture;
- (BOOL)unpackPVRData:(id)arg1;

@end

@interface GLKView : UIView <NSCoding>
{
    BOOL _inDraw;
    NSMutableDictionary *_drawableProperties;
    BOOL _shouldDeleteFramebuffer;
    unsigned int _resolveFramebuffer;
    unsigned int _resolveColorRenderbuffer;
    unsigned int _multisampleFramebuffer;
    unsigned int _multisampleColorRenderbuffer;
    unsigned int _depthRenderbuffer;
    unsigned int _stencilRenderbuffer;
    unsigned int _depthStencilRenderbuffer;
    id <GLKViewDelegate> _delegate;
    EAGLContext *_context;
    int _drawableWidth;
    int _drawableHeight;
    int _drawableColorFormat;
    int _drawableDepthFormat;
    int _drawableStencilFormat;
    int _drawableMultisample;
    BOOL _enableSetNeedsDisplay;
    void *_drawRectIMP;
}

+ (Class)layerClass;
@property(nonatomic) void *drawRectIMP; // @synthesize drawRectIMP=_drawRectIMP;
@property(readonly, nonatomic) int drawableHeight; // @synthesize drawableHeight=_drawableHeight;
@property(readonly, nonatomic) int drawableWidth; // @synthesize drawableWidth=_drawableWidth;
@property(nonatomic) id <GLKViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int depthStencilRenderbuffer; // @synthesize depthStencilRenderbuffer=_depthStencilRenderbuffer;
@property(nonatomic) unsigned int stencilRenderbuffer; // @synthesize stencilRenderbuffer=_stencilRenderbuffer;
@property(nonatomic) unsigned int depthRenderbuffer; // @synthesize depthRenderbuffer=_depthRenderbuffer;
@property(nonatomic) unsigned int multisampleColorRenderbuffer; // @synthesize multisampleColorRenderbuffer=_multisampleColorRenderbuffer;
@property(nonatomic) unsigned int multisampleFramebuffer; // @synthesize multisampleFramebuffer=_multisampleFramebuffer;
@property(nonatomic) unsigned int resolveColorRenderbuffer; // @synthesize resolveColorRenderbuffer=_resolveColorRenderbuffer;
@property(nonatomic) unsigned int resolveFramebuffer; // @synthesize resolveFramebuffer=_resolveFramebuffer;
@property(nonatomic) BOOL shouldDeleteFramebuffer; // @synthesize shouldDeleteFramebuffer=_shouldDeleteFramebuffer;
@property(retain, nonatomic) NSMutableDictionary *drawableProperties; // @synthesize drawableProperties=_drawableProperties;
@property(nonatomic) BOOL inDraw; // @synthesize inDraw=_inDraw;
- (void)layoutSubviews;
- (void)setContentScaleFactor:(float)arg1;
- (void)display;
- (BOOL)_controlsOwnScaleFactor;
- (BOOL)_canDrawContent;
- (void)displayLayer:(id)arg1;
@property(nonatomic) BOOL enableSetNeedsDisplay; // @synthesize enableSetNeedsDisplay=_enableSetNeedsDisplay;
- (id)snapshot;
- (void)bindDrawable;
@property(nonatomic) int drawableMultisample; // @synthesize drawableMultisample=_drawableMultisample;
@property(nonatomic) int drawableStencilFormat; // @synthesize drawableStencilFormat=_drawableStencilFormat;
@property(nonatomic) int drawableDepthFormat; // @synthesize drawableDepthFormat=_drawableDepthFormat;
@property(nonatomic) int drawableColorFormat; // @synthesize drawableColorFormat=_drawableColorFormat;
@property(retain, nonatomic) EAGLContext *context; // @synthesize context=_context;
- (void)_display:(BOOL)arg1;
- (BOOL)_presentFramebuffer;
- (void)_resolveAndDiscard;
- (void)_setFramebuffer:(char *)arg1;
- (void)_deleteFramebuffer;
- (void)deleteDrawable;
- (void)_createFramebuffer;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 context:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_initCommon;

@end

@interface GLKDisplayLinkMessenger : NSObject
{
    id _target;
}

- (void)message;
- (void)setTarget:(id)arg1;

@end

@interface GLKViewController : UIViewController <NSCoding, GLKViewDelegate>
{
    UIScreen *_screen;
    CADisplayLink *_displayLink;
    BOOL _displayLinkPaused;
    GLKDisplayLinkMessenger *_displayLinkMessenger;
    BOOL _viewIsVisible;
    BOOL _firstResumeOccurred;
    double _timeSinceFirstResumeStartTime;
    BOOL _lastResumeOccurred;
    double _timeSinceLastResumeStartTime;
    BOOL _lastUpdateOccurred;
    double _timeSinceLastUpdatePreviousTime;
    BOOL _lastDrawOccurred;
    double _timeSinceLastDrawPreviousTime;
    void *_updateIMP;
    id <GLKViewControllerDelegate> _delegate;
    int _screenFramesPerSecond;
    int _frameInterval;
    int _preferredFramesPerSecond;
    int _framesPerSecond;
    int _framesDisplayed;
    double _timeSinceFirstResume;
    double _timeSinceLastResume;
    double _timeSinceLastUpdate;
    double _timeSinceLastDraw;
    BOOL _pauseOnWillResignActive;
    BOOL _resumeOnDidBecomeActive;
}

@property(readonly, nonatomic) double timeSinceLastDraw; // @synthesize timeSinceLastDraw=_timeSinceLastDraw;
@property(readonly, nonatomic) double timeSinceLastUpdate; // @synthesize timeSinceLastUpdate=_timeSinceLastUpdate;
@property(readonly, nonatomic) int framesDisplayed; // @synthesize framesDisplayed=_framesDisplayed;
@property(readonly, nonatomic) int framesPerSecond; // @synthesize framesPerSecond=_framesPerSecond;
@property(nonatomic) int frameInterval; // @synthesize frameInterval=_frameInterval;
@property(nonatomic) int screenFramesPerSecond; // @synthesize screenFramesPerSecond=_screenFramesPerSecond;
@property(nonatomic) id <GLKViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) void *updateIMP; // @synthesize updateIMP=_updateIMP;
@property(nonatomic) double timeSinceLastDrawPreviousTime; // @synthesize timeSinceLastDrawPreviousTime=_timeSinceLastDrawPreviousTime;
@property(nonatomic) BOOL lastDrawOccurred; // @synthesize lastDrawOccurred=_lastDrawOccurred;
@property(nonatomic) double timeSinceLastUpdatePreviousTime; // @synthesize timeSinceLastUpdatePreviousTime=_timeSinceLastUpdatePreviousTime;
@property(nonatomic) BOOL lastUpdateOccurred; // @synthesize lastUpdateOccurred=_lastUpdateOccurred;
@property(nonatomic) double timeSinceLastResumeStartTime; // @synthesize timeSinceLastResumeStartTime=_timeSinceLastResumeStartTime;
@property(nonatomic) BOOL lastResumeOccurred; // @synthesize lastResumeOccurred=_lastResumeOccurred;
@property(nonatomic) double timeSinceFirstResumeStartTime; // @synthesize timeSinceFirstResumeStartTime=_timeSinceFirstResumeStartTime;
@property(nonatomic) BOOL firstResumeOccurred; // @synthesize firstResumeOccurred=_firstResumeOccurred;
@property(nonatomic) BOOL viewIsVisible; // @synthesize viewIsVisible=_viewIsVisible;
@property(retain, nonatomic) GLKDisplayLinkMessenger *displayLinkMessenger; // @synthesize displayLinkMessenger=_displayLinkMessenger;
@property(nonatomic) BOOL displayLinkPaused; // @synthesize displayLinkPaused=_displayLinkPaused;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) UIScreen *screen; // @synthesize screen=_screen;
- (void)glkView:(id)arg1 drawInRect:(struct CGRect)arg2;
@property(nonatomic) BOOL resumeOnDidBecomeActive; // @synthesize resumeOnDidBecomeActive=_resumeOnDidBecomeActive;
@property(nonatomic) BOOL pauseOnWillResignActive; // @synthesize pauseOnWillResignActive=_pauseOnWillResignActive;
@property(readonly, nonatomic) double timeSinceLastResume; // @synthesize timeSinceLastResume=_timeSinceLastResume;
@property(readonly, nonatomic) double timeSinceFirstResume; // @synthesize timeSinceFirstResume=_timeSinceFirstResume;
@property(nonatomic, getter=isPaused) BOOL paused;
@property(nonatomic) int preferredFramesPerSecond; // @synthesize preferredFramesPerSecond=_preferredFramesPerSecond;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)loadView;
- (void)setView:(id)arg1;
- (void)viewDidMoveToWindow:(id)arg1 shouldAppearOrDisappear:(BOOL)arg2;
- (void)_updateScreenIfChanged;
- (void)_resumeByNotification;
- (void)_pauseByNotification;
- (void)_updateAndDraw;
- (void)_createDisplayLinkForScreen:(id)arg1;
- (int)_calculateScreenFramesPerSecond:(id)arg1;
- (void)_configureNotifications;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;
- (void)_initCommon;

@end

@interface GLKTexture : NSObject
{
    NSData *imageData;
    struct CGImageBlockSet *_blockSet;
    struct __CFData *_cfData;
    unsigned int _width;
    unsigned int _height;
    unsigned int orientation;
    unsigned int numMipMapLevels;
    unsigned int bitsPerPixel;
    unsigned int _rowBytes;
    unsigned int nComponents;
    unsigned int nPrimarySurfaces;
    unsigned int nSurfaces;
    int loadMode;
    unsigned int texelFormat;
    unsigned int _dataCategory;
    unsigned int _index;
    unsigned int GLTextureName;
    unsigned int bindTarget;
    unsigned int textureTarget;
    unsigned int internalFormat;
    unsigned int format;
    unsigned int type;
    int _unpackAlignment;
    BOOL isPreMultipliedAlpha;
    BOOL isPowerOfTwo;
    BOOL _isCubeMap;
    BOOL isMipmapped;
    BOOL isVerticalFlipped;
    BOOL hasAlpha;
    BOOL reOrient;
    BOOL grayscaleAsAlpha;
    unsigned int _primarySurfaceLength;
    NSString *_label;
}

@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
@property(nonatomic) BOOL reOrient; // @synthesize reOrient;
@property(nonatomic) BOOL hasAlpha; // @synthesize hasAlpha;
@property(nonatomic) BOOL isVerticalFlipped; // @synthesize isVerticalFlipped;
@property(nonatomic) BOOL isMipmapped; // @synthesize isMipmapped;
@property(nonatomic) BOOL isCubeMap; // @synthesize isCubeMap=_isCubeMap;
@property(nonatomic) BOOL isPowerOfTwo; // @synthesize isPowerOfTwo;
@property(nonatomic) BOOL isPreMultipliedAlpha; // @synthesize isPreMultipliedAlpha;
@property(nonatomic) unsigned int nSurfaces; // @synthesize nSurfaces;
@property(nonatomic) unsigned int nPrimarySurfaces; // @synthesize nPrimarySurfaces;
@property(nonatomic) unsigned int nComponents; // @synthesize nComponents;
@property(nonatomic) unsigned int rowBytes; // @synthesize rowBytes=_rowBytes;
@property(nonatomic) unsigned int bitsPerPixel; // @synthesize bitsPerPixel;
@property(nonatomic) unsigned int numMipMapLevels; // @synthesize numMipMapLevels;
@property(nonatomic) unsigned int orientation; // @synthesize orientation;
@property(nonatomic) unsigned int height; // @synthesize height=_height;
@property(nonatomic) unsigned int width; // @synthesize width=_width;
@property(nonatomic) unsigned int type; // @synthesize type;
@property(nonatomic) unsigned int texelFormat; // @synthesize texelFormat;
@property(nonatomic) unsigned int format; // @synthesize format;
@property(nonatomic) unsigned int internalFormat; // @synthesize internalFormat;
@property(nonatomic) unsigned int textureTarget; // @synthesize textureTarget;
@property(nonatomic) unsigned int bindTarget; // @synthesize bindTarget;
@property(nonatomic) unsigned int index; // @synthesize index=_index;
@property(nonatomic) unsigned int dataCategory; // @synthesize dataCategory=_dataCategory;
@property(nonatomic) int loadMode; // @synthesize loadMode;
@property(nonatomic) unsigned int GLTextureName; // @synthesize GLTextureName;
@property(readonly) NSData *imageData; // @synthesize imageData;
- (BOOL)applyTextureOperations:(void *)arg1 source:(void *)arg2 withWidth:(unsigned int)arg3 withHeight:(unsigned int)arg4 withRowBytes:(unsigned int)arg5 error:(id *)arg6;
- (BOOL)determinePVRFormat:(unsigned int)arg1;
- (BOOL)determineCGImageBlockFormatWithComponentType:(int)arg1 andPixelSize:(unsigned long)arg2 andColorModel:(int)arg3;
- (BOOL)uploadToGLTexture:(unsigned int)arg1 error:(id *)arg2;
- (BOOL)_uploadToGLTexture:(unsigned int)arg1 data:(id)arg2 width:(int)arg3 height:(int)arg4 dataCategory:(int)arg5 cubeMapIndex:(int)arg6 mipMapIndex:(int)arg7 error:(id *)arg8;
- (BOOL)loadCGImage:(struct CGImage *)arg1 options:(id)arg2 error:(id *)arg3;
- (BOOL)loadWithData:(id)arg1 options:(id)arg2 error:(id *)arg3;
- (BOOL)decodeCGImage:(struct CGImage *)arg1 premultiplyAlpha:(BOOL)arg2;
- (BOOL)decodeCGImageImageProvider:(struct CGImage *)arg1 CGImageProvider:(struct CGImageProvider *)arg2 premultiplyAlpha:(BOOL)arg3;
- (BOOL)decodeCGImageDataProvider:(struct CGImage *)arg1;
- (void *)alignmentFix:(unsigned long)arg1 data:(const void *)arg2;
- (BOOL)loadPVRTCData:(id)arg1 error:(id *)arg2;
- (id)initWithDecodedData:(id)arg1 width:(unsigned int)arg2 height:(unsigned int)arg3 rowBytes:(unsigned int)arg4 texture:(id)arg5 cubeMapIndex:(int)arg6 options:(id)arg7 error:(id *)arg8;
- (id)initWithCGImage:(struct CGImage *)arg1 forceCubeMap:(BOOL)arg2 wasCubeMap:(char *)arg3 cubeMapIndex:(int)arg4 options:(id)arg5 error:(id *)arg6;
- (id)initWithData:(id)arg1 forceCubeMap:(BOOL)arg2 wasCubeMap:(char *)arg3 cubeMapIndex:(int)arg4 options:(id)arg5 error:(id *)arg6;
- (void)dealloc;
- (id)init;

@end

@interface GLKTextureInfo : NSObject <NSCopying>
{
    unsigned int name;
    unsigned int target;
    unsigned int width;
    unsigned int height;
    unsigned int alphaState;
    unsigned int textureOrigin;
    BOOL containsMipmaps;
}

@property(readonly) BOOL containsMipmaps; // @synthesize containsMipmaps;
@property(readonly) unsigned int textureOrigin; // @synthesize textureOrigin;
@property(readonly) unsigned int alphaState; // @synthesize alphaState;
@property(readonly) unsigned int height; // @synthesize height;
@property(readonly) unsigned int width; // @synthesize width;
@property(readonly) unsigned int target; // @synthesize target;
@property(readonly) unsigned int name; // @synthesize name;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithTexture:(id)arg1 textureName:(unsigned int)arg2;

@end

@interface GLKTextureLoader : NSObject
{
    EAGLContext *_eaglContext;
    NSLock *_nsLock;
}

+ (id)cubeMapWithContentsOfURL:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)cubeMapWithContentsOfFile:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)cubeMapWithContentsOfFiles:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)textureWithCGImage:(struct CGImage *)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)textureWithContentsOfData:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)textureWithContentsOfURL:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)textureWithContentsOfFile:(id)arg1 options:(id)arg2 error:(id *)arg3;
+ (id)commonCubeMapWithContentsOfURL:(id)arg1 options:(id)arg2 error:(id *)arg3 lock:(id)arg4 eaglContext:(id)arg5;
+ (id)commonCubeMapWithContentsOfFiles:(id)arg1 options:(id)arg2 error:(id *)arg3 lock:(id)arg4 eaglContext:(id)arg5;
+ (id)commonTextureWithCGImage:(struct CGImage *)arg1 options:(id)arg2 error:(id *)arg3 lock:(id)arg4 eaglContext:(id)arg5;
+ (id)commonTextureWithContentsOfURL:(id)arg1 options:(id)arg2 error:(id *)arg3 lock:(id)arg4 eaglContext:(id)arg5;
+ (id)commonTextureWithContentsOfData:(id)arg1 options:(id)arg2 error:(id *)arg3 lock:(id)arg4 eaglContext:(id)arg5;
+ (id)_textureWithTexture:(id)arg1 error:(id *)arg2;
+ (void)unlockAndRestoreContext:(id)arg1 eaglContext:(id)arg2;
+ (id)lockAndSwitchContext:(id)arg1 eaglContext:(id)arg2;
@property(retain) NSLock *nsLock; // @synthesize nsLock=_nsLock;
@property(retain) EAGLContext *eaglContext; // @synthesize eaglContext=_eaglContext;
- (void)cubeMapWithContentsOfURL:(id)arg1 options:(id)arg2 queue:(struct dispatch_queue_s *)arg3 completionHandler:(id)arg4;
- (void)cubeMapWithContentsOfFile:(id)arg1 options:(id)arg2 queue:(struct dispatch_queue_s *)arg3 completionHandler:(id)arg4;
- (void)cubeMapWithContentsOfFiles:(id)arg1 options:(id)arg2 queue:(struct dispatch_queue_s *)arg3 completionHandler:(id)arg4;
- (void)textureWithCGImage:(struct CGImage *)arg1 options:(id)arg2 queue:(struct dispatch_queue_s *)arg3 completionHandler:(id)arg4;
- (void)textureWithContentsOfData:(id)arg1 options:(id)arg2 queue:(struct dispatch_queue_s *)arg3 completionHandler:(id)arg4;
- (void)textureWithContentsOfURL:(id)arg1 options:(id)arg2 queue:(struct dispatch_queue_s *)arg3 completionHandler:(id)arg4;
- (void)textureWithContentsOfFile:(id)arg1 options:(id)arg2 queue:(struct dispatch_queue_s *)arg3 completionHandler:(id)arg4;
- (void)dealloc;
- (id)initWithSharegroup:(id)arg1;

@end

@interface GLKSkyboxEffect : NSObject <GLKNamedEffect>
{
    union _GLKVector3 _center;
    float _xSize;
    float _ySize;
    float _zSize;
    GLKEffectPropertyTexture *_textureCubeMap;
    GLKEffectPropertyTransform *_transform;
    NSString *_label;
    unsigned int _vao;
    unsigned int _positionVBO;
    unsigned int _texCoordVBO;
    NSMutableArray *_propertyArray;
    unsigned char _effectStale;
    GLKEffect *_effect;
    unsigned int _programName;
}

@property(readonly, nonatomic) GLKEffectPropertyTransform *transform; // @synthesize transform=_transform;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
@property(nonatomic) unsigned int programName; // @synthesize programName=_programName;
@property(nonatomic) GLKEffect *effect; // @synthesize effect=_effect;
@property(nonatomic) unsigned char effectStale; // @synthesize effectStale=_effectStale;
@property(readonly, nonatomic) NSMutableArray *propertyArray; // @synthesize propertyArray=_propertyArray;
@property(nonatomic) unsigned int texCoordVBO; // @synthesize texCoordVBO=_texCoordVBO;
@property(nonatomic) unsigned int positionVBO; // @synthesize positionVBO=_positionVBO;
@property(nonatomic) unsigned int vao; // @synthesize vao=_vao;
@property(readonly, nonatomic) GLKEffectPropertyTexture *textureCubeMap; // @synthesize textureCubeMap=_textureCubeMap;
@property(nonatomic) float zSize; // @synthesize zSize=_zSize;
@property(nonatomic) float ySize; // @synthesize ySize=_ySize;
@property(nonatomic) float xSize; // @synthesize xSize=_xSize;
@property(nonatomic) union _GLKVector3 center; // @synthesize center=_center;
- (id)description;
- (void)dealloc;
- (void)draw;
- (void)prepareToDraw;
- (void)updateSkyboxEffect;
- (void)createAndBindVAOWithPositions:(float *)arg1 texCoords:(float *)arg2;
- (id)init;

@end

@interface GLKReflectionMapEffect : GLKBaseEffect <GLKNamedEffect>
{
    GLKEffectPropertyTexture *_textureCubeMap;
    union _GLKMatrix3 _matrix;
    BOOL _dirtyUniforms;
    int _matrixLoc;
}

@property(nonatomic) int matrixLoc; // @synthesize matrixLoc=_matrixLoc;
@property(nonatomic) union _GLKMatrix3 matrix; // @synthesize matrix=_matrix;
@property(nonatomic) BOOL dirtyUniforms; // @synthesize dirtyUniforms=_dirtyUniforms;
@property(readonly, nonatomic) GLKEffectPropertyTexture *textureCubeMap; // @synthesize textureCubeMap=_textureCubeMap;
- (id)description;
- (void)dealloc;
- (void)prepareToDraw;
- (id)init;

@end

@interface GLKShaderBlockNode : NSObject <NSXMLParserDelegate, NSCopying>
{
    struct GLKBigInt_s _mask;
    GLKShaderBlockNode *_parent;
    GLKShaderBlockNode *_next;
    GLKShaderBlockNode *_children;
    NSString *_label;
    NSString *_loopVar;
    int _type;
    int _unrollCt;
    unsigned int _index;
    NSMutableString *_blockText;
    int _propertyClass;
    BOOL _indexedMask;
}

+ (void)printTreeVerbose:(id)arg1;
+ (void)printTree:(id)arg1;
+ (void)setIndicesForRoot:(id)arg1 andReplaceLoopVar:(id)arg2 baseLabel:(id)arg3 basePropertyClass:(int)arg4 usingIndex:(unsigned int)arg5 indexString:(id)arg6;
+ (unsigned int)nodeCt:(id)arg1 nodeCt:(unsigned int *)arg2;
+ (void)insertNode:(id)arg1 afterSibling:(id)arg2;
+ (void)buildUnrollNodeArray:(id)arg1 array:(id)arg2;
+ (void)setMasksWithRoot:(id)arg1 treeRoot:(id)arg2 mask:(struct GLKBigInt_s *)arg3;
+ (struct GLKBigInt_s)maskForLabel:(id)arg1 root:(id)arg2 index:(int)arg3;
+ (id)copyTreeWithRoot:(id)arg1 parent:(id)arg2;
@property(nonatomic) BOOL indexedMask; // @synthesize indexedMask=_indexedMask;
@property(nonatomic) unsigned int index; // @synthesize index=_index;
@property(nonatomic) int propertyClass; // @synthesize propertyClass=_propertyClass;
@property(retain, nonatomic) NSMutableString *blockText; // @synthesize blockText=_blockText;
@property(nonatomic) int unrollCt; // @synthesize unrollCt=_unrollCt;
@property(nonatomic) struct GLKBigInt_s mask; // @synthesize mask=_mask;
@property(nonatomic) GLKShaderBlockNode *children; // @synthesize children=_children;
@property(nonatomic) GLKShaderBlockNode *next; // @synthesize next=_next;
@property(nonatomic) GLKShaderBlockNode *parent; // @synthesize parent=_parent;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *loopVar; // @synthesize loopVar=_loopVar;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
- (void)dealloc;
- (id)description;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

@interface GLKHashableBigInt : NSObject
{
    struct GLKBigInt_s _bigInt;
}

- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithBigInt:(struct GLKBigInt_s *)arg1;

@end

@interface GLKShadingHash : NSObject
{
    NSLock *_vshLock;
    NSLock *_fshLock;
    NSMutableDictionary *_compiledVshs;
    NSMutableDictionary *_compiledFshs;
}

- (void)dealloc;
- (id)compiledFshForKey:(id)arg1;
- (void)setCompiledFsh:(id)arg1 forKey:(id)arg2;
- (id)compiledVshForKey:(id)arg1;
- (void)setCompiledVsh:(id)arg1 forKey:(id)arg2;
- (id)init;

@end

